version: '2'
services:
  app:
    image: lukeswart/township-server:release-0.0.1
    volumes:
      - ~/db:/server/db
      - ./set-timezone.sh:/set-timezone.sh
    environment:
      - PORT=${TOWNSHIP_PORT}
      - NODE_ENV=${NODE_ENV}
      - SECRET=${SECRET}
      - TZ=${TZ}
    restart: always
    command: sh -c "/set-timezone.sh && git fetch && git checkout master && git pull --rebase && ./start.sh"

  letsencrypt:
    image: lukeswart/letsencrypt
    entrypoint: ""
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80"
      - "443"
    environment:
      - TERM=xterm
      - LETSENCRYPT_DOMAINS=${LETSENCRYPT_DOMAINS}
      - LETSENCRYPT_DEBUG_MODE=${LETSENCRYPT_DEBUG_MODE}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

  nginx:
    image: lukeswart/nginx-letsencrypt
    volumes:
      - ./nginx-acme-challenge-envsubst.conf:/etc/nginx/nginx.conf
      - ./nginx-envsubst.conf:/etc/nginx/nginx-secure.conf
    links:
      - app
    volumes_from:
      - letsencrypt
    environment:
      - MY_DOMAIN_NAME=${MY_DOMAIN_NAME}
    ports:
      - 80:80
      - 443:443
    restart: always

  # Our cron container that runs our letsencrypt container, and reloads our nginx container
  letsencrypt-nginx-cron:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt-nginx-cron:/etc/cron.d/letsencrypt-nginx-cron
    # environment:
    #   - TZ=${TZ}
    # TODO: automate timezone script
    command: sh -c "apk add --update tzdata && cp /usr/share/zoneinfo/US/Pacific /etc/localtime && echo 'America/Los_Angeles' > /etc/timezone && date && apk del tzdata && chmod a+x /etc/cron.d/letsencrypt-nginx-cron && touch /var/log/crond.log && crontab /etc/cron.d/letsencrypt-nginx-cron && crond -l 0 -L /var/log/crond.log && echo 'starting nginx-cron' && tail -f /var/log/crond.log"
